In [19]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [26]:
data1=pd.read_csv("data/INP_PP_CAB18.csv", sep=",", encoding="latin_1")
data2=pd.read_csv("data/INP_INP20231025195756.csv", sep=",", encoding="latin_1")

In [22]:
data1.head()
#data1.describe()

,Año,Mes,Fecha_Pub_DOF,Clave ciudad,Nombre ciudad,División,Grupo,Clase,Subclase,Clave genérico,Genérico,Consecutivo,Especificación,Precio promedio,Cantidad,Unidad,Estatus
0,2023,9,NaN,19,"Chihuahua, Chih.","1. Alimentos, bebidas y tabaco",1.1. Alimentos,"1.1.1. Pan, tortillas y cereales",04 Arroz y cereales preparados,1,Arroz,1,"MYBRAND, BLANCO, SUPER EXTRA, BOLSA DE 906 GR ...",24.17,1,KG,NaN
1,2023,9,NaN,19,"Chihuahua, Chih.","1. Alimentos, bebidas y tabaco",1.1. Alimentos,"1.1.1. Pan, tortillas y cereales",04 Arroz y cereales preparados,1,Arroz,2,"PAISA, BLANCO, SUPER EXTRA, BOLSA DE 907 GR ...",24.15,1,KG,NaN
2,2023,9,NaN,19,"Chihuahua, Chih.","1. Alimentos, bebidas y tabaco",1.1. Alimentos,"1.1.1. Pan, tortillas y cereales",04 Arroz y cereales preparados,1,Arroz,3,"ALIMENTOS CAZEROLA, BLANCO, EXTRA, LARGO, BOLS...",22.49,1,KG,NaN
3,2023,9,NaN,19,"Chihuahua, Chih.","1. Alimentos, bebidas y tabaco",1.1. Alimentos,"1.1.1. Pan, tortillas y cereales",04 Arroz y cereales preparados,1,Arroz,4,"VERDE VALLE, BLANCO, EXTRA, BOLSA DE 250 GR ...",48.00,1,KG,NaN
4,2023,9,NaN,19,"Chihuahua, Chih.","1. Alimentos, bebidas y tabaco",1.1. Alimentos,"1.1.1. Pan, tortillas y cereales",04 Arroz y cereales preparados,1,Arroz,5,"SCHETTINO, BLANCO, SUPER EXTRA, BOLSA DE 907 G...",18.19,1,KG,NaN

In [28]:
data2.head()
data2.describe()

,ï¿½ndices.1,ï¿½ndices.2,ï¿½ndices.3,ï¿½ndices.4,ï¿½ndices.5,ï¿½ndices.6,ï¿½ndices.7,ï¿½ndices.8,ï¿½ndices.10,ï¿½ndices.11,...,ï¿½ndices.457,ï¿½ndices.458,ï¿½ndices.461,ï¿½ndices.464,ï¿½ndices.465,ï¿½ndices.470,ï¿½ndices.473,ï¿½ndices.474,ï¿½ndices.492,ï¿½ndices.557
count,513.000000,513.000000,513.000000,513.000000,513.000000,513.000000,513.000000,513.000000,513.000000,513.000000,...,513.000000,513.000000,513.000000,513.000000,513.000000,513.000000,513.000000,513.000000,513.000000,513.000000
mean,40.740068,42.183004,50.149486,48.344819,52.265942,46.251252,53.917992,55.803725,53.829547,49.833190,...,44.664996,49.191162,38.854903,50.557113,49.542559,47.477722,48.119522,50.833060,66.316393,45.921641
std,43.119003,36.739400,39.225976,44.522033,41.389481,41.317332,42.354137,43.321640,50.266372,45.663495,...,36.600591,36.069322,36.442871,35.653495,35.507381,35.728693,36.607227,36.163877,38.321316,36.572098
min,0.042336,0.031683,0.102459,0.078517,0.054115,0.078021,0.131956,0.060930,0.025202,0.064281,...,0.029738,0.057968,0.010161,0.018096,0.023095,0.046770,0.050048,0.101191,0.110682,0.039929
25%,7.262401,9.285346,15.666838,11.814929,14.892239,10.957628,16.806131,16.767608,10.131323,12.877209,...,5.166216,15.012926,5.315041,20.868764,16.400803,9.228489,8.825260,14.786177,28.442252,9.837960
50%,24.649119,29.781732,41.076404,34.134333,51.763248,32.116403,44.016003,58.281757,42.420263,40.024325,...,45.144957,53.257574,33.426137,56.271752,59.474080,50.756850,51.316737,56.401745,85.874773,44.968913
75%,66.236934,68.098186,84.475140,84.524617,84.439900,84.669712,93.549169,87.010527,85.882348,71.069894,...,78.046121,79.822767,55.385633,79.020849,77.585227,76.303877,77.331394,80.701453,96.831321,72.669182
max,159.218110,123.620478,137.072226,189.617840,166.905565,157.772342,170.380438,178.404351,205.465345,231.134615,...,117.770393,114.383686,127.640663,120.926500,118.791107,120.041362,119.212536,118.989265,120.849964,115.955456